# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('numeroInt', models.CharField(blank=True, max_length=9)),
                ('codigoPostal', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('pais', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=100)),
                ('capacidadPersonas', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('monedaCambio', models.CharField(max_length=30)),
                ('asientos', models.BooleanField()),
                ('secciones', models.BooleanField()),
            ],
        ),
    ]
