# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20160607_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='secciones',
        ),
        migrations.AddField(
            model_name='seccion',
            name='venue',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='eventos.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='imagen',
            field=models.ImageField(default=2, upload_to='venues-img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='seccion',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
