# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20160607_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('artista', models.CharField(max_length=30)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venueEvento', to='eventos.Venue')),
            ],
        ),
        migrations.AlterField(
            model_name='seccion',
            name='costoSeccion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='numeroAsientosSeccion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venueSecciones', to='eventos.Venue'),
        ),
    ]
