# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20160607_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('costo', models.IntegerField()),
                ('integrantes', models.IntegerField()),
                ('espectadores', models.IntegerField()),
                ('asistentesPorConcierto', models.IntegerField()),
                ('discoReciente', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='artist-img')),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistaEvento', to='eventos.Artista'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='ciudad',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='venue',
            name='estado',
            field=models.CharField(max_length=40),
        ),
    ]
