# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20160608_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='monedaCambio',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
